/**
 * Squidex API for okahyaoglunet App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProjectDescriptionProperty } from './projectDescriptionProperty';
import { ProjectImageFolderNameProperty } from './projectImageFolderNameProperty';
import { ProjectImagesProperty } from './projectImagesProperty';
import { ProjectLinkProperty } from './projectLinkProperty';
import { ProjectOrderProperty } from './projectOrderProperty';
import { ProjectSubtitleProperty } from './projectSubtitleProperty';
import { ProjectThumbsProperty } from './projectThumbsProperty';
import { ProjectTitleProperty } from './projectTitleProperty';
export interface ProjectDto {
    /**
     * Title
     */
    title?: ProjectTitleProperty;
    /**
     * Subtitle
     */
    subtitle?: ProjectSubtitleProperty;
    /**
     * Description
     */
    description?: ProjectDescriptionProperty;
    /**
     * Order
     */
    order: ProjectOrderProperty;
    /**
     * Link
     */
    link?: ProjectLinkProperty;
    /**
     * ImageFolderName
     */
    imageFolderName?: ProjectImageFolderNameProperty;
    /**
     * Images
     */
    images?: ProjectImagesProperty;
    /**
     * Thumbs
     */
    thumbs?: ProjectThumbsProperty;
}
